name: Tests
on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  test:
    name: 'Test on Node v${{ matrix.node }} ${{ matrix.os.name }} ${{ matrix.arch }}'
    runs-on: ${{ matrix.os.name }}-${{ matrix.os.version }}

    strategy:
      matrix:
        os:
          - name: Ubuntu
            version: latest
          - name: macOS
            version: latest
          - name: Windows
            version: 2019
        node: ['12','13','14','15','16','17','18','19']
        arch: [x64]
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - name: 'Install Linux dependencies'
        if: ${{ matrix.os.name == 'Ubuntu' }}
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev
      - name: 'Install npm@^6'
        if: ${{matrix.node == '12'}}
        run: npm install --global npm@6.14.17
      - name: 'Install npm@^7'
        if: ${{ (matrix.node == '13') || (matrix.node == '15')}}
        run: npm install --global npm@7.24.2
      - name: 'Install npm@^8'
        if: ${{(matrix.node != '12') && (matrix.node != '13') && (matrix.node != '15')}}
        run: npm install --global npm@8.3.1
      - name: Install
        run: npm ci
      - name: Compile
        run: npm run compile
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm test